directories:
  output: publish
  buildResources: build
appId: lucifer
files:
  - filter:
      - '*.js'
      - '*.html'
      - package.json
      - yarn.lock
      - node_modules
      - images
mac:
  icon: ./images/icon.icns
asar: true
compression: maximum
electronVersion: 5.0.6
